#!/bin/bash

FULL=$1
MODE=$2
FILE=${FULL##*/}
EXT=${FILE#*.}

function join(){
	local IFS=';'; echo "$*";
}
function java_main {
	grep -rl --text "main...(\[Ljava/lang/String;)V" . | sed -n 's:.\/\([^$]*\)\.class:\1:p' | tail -1 | tr / .
}

function first_line {
	local LINE=$(head -n 1 "$FULL")

	if [[ $LINE == *"#!"* ]]; then
		chmod +x "$FULL"; "$FULL"
		exit; fi
	if [[ $LINE == *">>"* ]]; then
		eval "${LINE#*>>*}"
		exit; fi
}
function find_root {
	while [ "$PWD" != "/" ]; do
		if [ -f ".project" ]; then
			local LINE=$(head -n 1 .project)
			if [[ "$LINE" == "+"* ]]; then
				ARGS=${LINE#+*}
			elif [ -n "$LINE" ]; then
				eval "$LINE"
				exit
			fi
			FILE="./**/*.$EXT"
			OUT="bin/${PWD##*/}"
			return 0
		fi
		cd .. 
	done

	cd "${FULL%/*}"
	OUT="${FILE%%.*}"
}
function compile_ext {
	case $EXT in
	"c" | "h")
		gcc -pedantic -g -std=c11 -O3 -Wall -Wextra -o $OUT $FILE $ARGS ;;
	"scala")
		fsc -cp $(join lib/*.jar ""). $FILE ;;
	"rs")
		rustc -A dead_code -A unused_variables $FILE ;;
	"java")
		case $MODE in
		"norm")
			javac $FILE
			jar cfe $OUT.jar $(java_main) ./*.class ;;
		"shift")
			ant debug ;;
		esac ;;
	esac
}
function run_ext {
	case $EXT in
	"scala")
		scala -cp $(join lib/*.jar ""). $(java_main) ;;
	"java")
		case $MODE in
		"norm")
			java -jar $OUT.jar ;;
		"shift")
			adb install -r bin/*-debug.apk
			adb shell am start -a android.intent.action.MAIN -n $ARGS
			adb logcat ;;
		esac ;;
	"hs")
		ghci -Wall $FILE ;;
	"js")
		node $FILE ;;
	"jade")
		jade -P $FILE ;;
	*)
		./$OUT ;;
	esac
}

tput reset
shopt -s nullglob
cd "${FULL%/*}"
clear

first_line
find_root

compile_ext
run_ext
