#!/bin/bash

i3-msg "workspace 2; exec pixel"
sleep 0.8
i3-msg "floating toggle; focus right; move container workspace 6; floating toggle; border pixel 0; exec urxvt"
sleep 0.1
i3-msg "resize grow width 353px; border pixel 0"
